# https://golangci-lint.run/usage/configuration/#run-configuration
# https://golangci-lint.run/usage/false-positives/
linters:
  # https://golangci-lint.run/usage/linters/
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - ginkgolinter
    - gofmt
    - govet
    - staticcheck
    - revive #dotimport
    # - golint // Deprecated

issues:
  exclude-rules:
    - path-except: '(.+)_test\.go'
      linters:
        - revive

  # - path: '(.+)_test\.go'
  #   text: "dot-imports: should not use dot imports (revive)"
  # - path: 'pkg/imagevector/imagevector_test.go'
  #   text: "dot-imports: should not use dot imports (revive)"

# linters-settings:
#   revive:
#     rules:
#       # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
#       - name: dot-imports
#         severity: warning
#         disabled: true #default for golangci - false 
