# https://golangci-lint.run/usage/configuration/#run-configuration
# https://golangci-lint.run/usage/false-positives/
linters:
  # https://golangci-lint.run/usage/linters/
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - ginkgolinter
    - gofmt
    - govet
    - staticcheck
    - revive
    # - golint // Deprecated

issues:
  exclude-rules:
  # There were problems when the master didn't pass the linter checks
  # because the check was a warning.
  # dot imports are used just for tests - ginko and gomega.
    - path: '(.+)_test\.go'
      text: '.*should not use dot imports.*'
      linters:
        - revive
