# https://golangci-lint.run/usage/configuration/#run-configuration
# https://golangci-lint.run/usage/false-positives/
linters:
  # https://golangci-lint.run/usage/linters/
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - ginkgolinter
    - gofmt
    - govet
    - staticcheck
    - revive
    # - golint // Deprecated

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      #source: "dot-import"
      #   text: '.*not.*'
      text: '.*should not use dot imports.*'
      linters:
        - revive

linters-settings:
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
      - name: dot-imports
        severity: error
        disabled: false #default for golangci - false 
