# Copyright 2022 Intel Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{/* dynamic configuration have different form than static configs - are read by cri-agent */}}
{{- range $configName, $configContent := (.Values.configs | default dict).dynamic }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: "cri-resmgr-config.{{ $configName}}"
data:
{{- $configObject := fromYaml $configContent }}
{{- range $configKey, $configValue := $configObject }}
  {{ $configKey }}: |
    {{- $configValue | toYaml | nindent 4 }}
{{- end }}
---

{{- end }}
