# Copyright 2022 Intel Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-cri-resmgr-monitoring-scrape-config
  namespace: {{ namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  scrape_config: |
    - job_name: cri-rm
      honor_timestamps: true
      # scrape_interval should be the same as EXTRA_OPTIONS="--metrics-interval Xs" for extension configs
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: https
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      tls_config:
        ca_file: /etc/prometheus/seed/ca.crt
        insecure_skip_verify: false
      follow_redirects: true
      enable_http2: true
      kubernetes_sd_configs:
      - api_server: https://kube-apiserver:443
        role: endpoints
        kubeconfig_file: ""
        authorization:
          type: Bearer
          credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
        tls_config:
          ca_file: /etc/prometheus/seed/ca.crt
          insecure_skip_verify: false
        follow_redirects: true
        enable_http2: true
      relabel_configs:
      - separator: ;
        regex: (.*)
        target_label: type
        replacement: shoot
        action: replace
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: cri-resmgr-installation;metrics
        replacement: $1
        action: keep
      - separator: ;
        regex: __meta_kubernetes_service_label_(.+)
        replacement: $1
        action: labelmap
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: (.*)
        target_label: node
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: kube-apiserver:443
        action: replace
      - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number]
        separator: ;
        regex: (.+);(.+)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-system/pods/${1}:${2}/proxy/metrics
        action: replace
