# Copyright 2022 Intel Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local2
  namespace: garden-local
  annotations:
    shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds: "0"
spec:
  seedName: local
  cloudProfileName: local
  secretBindingName: local
  region: local
  ### In shoot local2 extension is required and not disabled with own config to test override.
  extensions:
    - type: cri-resmgr-extension
      disabled: false
      providerConfig:
        ### NodeSelector limits on which group of workers the cri will be uploaded
        nodeSelector:
          # worker.gardener.cloud/pool: local
        configs:
          ### Those options are passed directly to cri-resmgr binary.
          ### Should be the same value in pkg/consts/monitoring.yaml for scrape_interval
          EXTRA_OPTIONS: |
            EXTRA_OPTIONS="--metrics-interval 5s"
          ### This is *dynamic* config that will be applied by cri-resmgr-agent
          default: |
            policy:
              Active: balloons
              AvailableResources:
                CPU: cpuset:1-15
              ReservedResources:
                CPU: cpuset:1
              balloons:
                BalloonTypes:
                  - Name: "some-special-balloon-for-shoot2"
                    MinCPUs: 3
                    MaxCPUs: 3
                    MinBalloons: 2
            logger:
              Debug: resource-manager,cache,policy,config-server
              Klog:
                skip_headers: true
            instrumentation:
              HTTPEndpoint: :8891
              PrometheusExport: true
          ### This is *static* initial configuration file that will be passed do systemd unit
          fallback: |
            policy:
              Active: balloons
              AvailableResources:
                CPU: cpuset:1-15
              ReservedResources:
                CPU: 1
            logger:
              Debug: resource-manager,cache,policy,config-server
              Klog:
                skip_headers: true
            instrumentation:
              HTTPEndpoint: :8891
              PrometheusExport: true

  networking:
    type: calico
    providerConfig:
      apiVersion: calico.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
      backend: none
      typha:
        enabled: false
  provider:
    type: local
    workers:
      - name: local
        machine:
          type: local
        cri:
          name: containerd
        minimum: 1
        maximum: 1
        maxSurge: 1
        maxUnavailable: 0
  kubernetes:
    version: 1.25.4
